name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  commitlint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install required dependencies
        run: |
          npm install @commitlint/config-conventional commitlint@latest --save-dev

      - name: Print versions
        run: |
          git --version
          node --version
          npm --version
          npx commitlint --version

      - name: Validate first commit with commitlint
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        run: |
          first_commit=$(git rev-list --max-parents=0 HEAD)
          git log -1 $first_commit --pretty=format:%B | npx commitlint

  wpm-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install required dependencies
        run: |
          set -e
          sudo apt-get update
          sudo apt-get install -y zsh
          curl -L -o jq https://github.com/jqlang/jq/releases/download/jq-1.7/jq-linux64
          chmod +x jq
          sudo mv jq /usr/local/bin/jq

      - name: Run wpm_test tests
        run: |
          TERM=xterm zsh -c "source wpm.plugin.zsh; wpm_test -f words_top-250-english-easy.txt -d 0"

      - name: Validate stats.json
        run: |
          expected_content=$(cat <<EOF
          {"words_top-250-english-easy.txt": {"average": {"wpm": 0, "accuracy": 0, "tests taken": 1}, "results": [{"date":"$(date +"%m/%d/%Y%l:%M%p")","wpm":0,"test duration":0,"keystrokes":0,"accuracy":0,"correct":0,"incorrect":0}]}}
          EOF
          )
          actual_content=$(cat stats/stats.json)
          echo "Expected stats.json content"
          echo "$expected_content"
          echo "Actual stats.json content"
          echo "$actual_content"
          if [ "$actual_content" != "$expected_content" ]; then
            echo "stats.json content does not match expected content"
            exit 1
          fi
