name: CI

on: [push, pull_request]

jobs:
  commitlint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install required dependencies
        run: |
          npm install @commitlint/config-conventional commitlint@latest --save-dev

      - name: Print versions
        run: |
          git --version
          node --version
          npm --version
          npx commitlint --version

      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: npx commitlint --last --verbose

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose

  wpm-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Zsh and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y zsh
          brew install jq@1.7
          echo "TESTING"
          jq --version

      - name: Create empty stats.json file
        run: |
          mkdir -p wpm/stats
          echo "{}" > wpm/stats/stats.json

      - name: Run wpm_test
        run: |
          TERM=dumb zsh <<EOF
          source wpm.plugin.zsh
          echo 3 | wpm_test 10
          EOF

      - name: Compare stats.json to expected content
        run: |
          expected_content='{"words_top-250-english-easy.txt": {"average": {"wpm": 0, "accuracy": 0, "tests taken": 1}, "results": [{"date":"$(date +"%m/%d/%Y%l:%M%p")","wpm":0,"test duration":10,"keystrokes":0,"accuracy":0,"correct":0,"incorrect":0}]}}'
          actual_content=$(cat wpm/stats/stats.json)
          if [ "$actual_content" != "$expected_content" ]; then
            echo "stats.json content does not match expected content"
            exit 1
          fi
